export interface Tip {
  id: string;
  category: "candles" | "resin" | "concrete" | "plaster" | "soap" | "general" | "business";
  emoji: string;
  es: string;
  en: string;
}

export const TIPS: Tip[] = [
  // CANDLES
  { id: "c1", category: "candles", emoji: "🌡️", es: "Para cera de soya, añade la fragancia a 75–80°C. Si la temperatura es muy alta se evapora el aroma; muy baja y no se incorpora bien.", en: "For soy wax, add fragrance at 75–80°C. Too hot and the scent evaporates; too cool and it won't bind properly." },
  { id: "c2", category: "candles", emoji: "🕯️", es: "La cera de molde siempre necesita una segunda vertida. El centro se hunde al enfriarse — reserva un 15% de cera para rellenarlo.", en: "Mold wax always needs a second pour. The center sinks as it cools — keep 15% of wax to refill it." },
  { id: "c3", category: "candles", emoji: "🧪", es: "La carga máxima de fragancia en cera de soya es 12%. Superar ese límite causa 'sweating' — gotitas de aceite en la superficie.", en: "Max fragrance load for soy wax is 12%. Exceeding it causes 'sweating' — oil droplets on the surface." },
  { id: "c4", category: "candles", emoji: "🔥", es: "Vierte la cera de soya entre 60–65°C para evitar manchas blancas (frosting). Cuanto más lento se enfríe, mejor queda la superficie.", en: "Pour soy wax at 60–65°C to avoid white spots (frosting). The slower it cools, the better the surface." },
  { id: "c5", category: "candles", emoji: "🪔", es: "El Vybar 103 es específico para parafina de molde. Si usas cera blanda como soya o coco, usa Vybar 260 para mejor retención de fragancia.", en: "Vybar 103 is for paraffin mold candles. For soft waxes like soy or coconut, use Vybar 260 for better scent retention." },
  { id: "c6", category: "candles", emoji: "💡", es: "Para calcular el pabilo correcto, mide el diámetro de tu vela. Como regla general: velas de 5–7 cm necesitan pabilo CD-12 o ECO-6.", en: "To pick the right wick, measure your candle's diameter. General rule: 5–7 cm candles need CD-12 or ECO-6 wick." },
  { id: "c7", category: "candles", emoji: "🌿", es: "La cera de coco tiene el punto de fusión más bajo (35–45°C). Es ideal para velas en envase pero no funciona en moldes rígidos.", en: "Coconut wax has the lowest melting point (35–45°C). It's ideal for container candles but won't work in rigid molds." },
  { id: "c8", category: "candles", emoji: "🎨", es: "Para velas de colores vibrantes, usa colorantes específicos para cera (no tintes textiles). Los tintes en polvo dan más control que los líquidos.", en: "For vibrant candle colors, use wax-specific dyes (not textile dyes). Powder dyes give more control than liquid ones." },
  { id: "c9", category: "candles", emoji: "⏱️", es: "Deja curar tus velas al menos 48 horas antes de probarlas. La fragancia y la cera necesitan 'asentarse' para dar el mejor aroma.", en: "Let your candles cure for at least 48 hours before testing. Fragrance and wax need to 'settle' for the best scent throw." },
  { id: "c10", category: "candles", emoji: "🏠", es: "El 'cold throw' es el aroma sin quemar, el 'hot throw' es el aroma al quemarse. Un buen hot throw requiere la carga de fragancia y el pabilo correctos.", en: "Cold throw is unlit scent, hot throw is lit scent. Good hot throw requires both correct fragrance load and the right wick." },
  { id: "c11", category: "candles", emoji: "📏", es: "Para velas de molde: precalienta el molde a 40–50°C. Reduce el choque térmico y da una superficie más uniforme.", en: "For mold candles: pre-warm the mold to 40–50°C. It reduces thermal shock and gives a more uniform surface." },
  { id: "c12", category: "candles", emoji: "🧴", es: "Aplica desmoldante (aceite de bebé, spray de silicona) dentro del molde antes de verter. Facilitará enormemente el desmolde sin dañar la superficie.", en: "Apply mold release (baby oil, silicone spray) inside the mold before pouring. It makes demolding much easier without damaging the surface." },

  // RESIN
  { id: "r1", category: "resin", emoji: "⚗️", es: "Mezcla siempre Parte A + Parte B durante al menos 3 minutos raspando bien los bordes y el fondo del recipiente. La resina mal mezclada nunca cura bien.", en: "Always mix Part A + Part B for at least 3 minutes, scraping the sides and bottom. Poorly mixed resin will never cure properly." },
  { id: "r2", category: "resin", emoji: "🌡️", es: "La temperatura ideal para trabajar resina es 22–26°C. Por debajo de 18°C la resina se vuelve más viscosa y puede no curar correctamente.", en: "The ideal working temperature for resin is 22–26°C. Below 18°C, resin becomes too viscous and may not cure properly." },
  { id: "r3", category: "resin", emoji: "🫧", es: "Para eliminar burbujas en resina: usa una pistola de calor a 5–10 cm de distancia con movimientos rápidos. El soplete de joyería funciona aún mejor.", en: "To remove resin bubbles: use a heat gun at 5–10 cm distance with quick movements. A jewelry torch works even better." },
  { id: "r4", category: "resin", emoji: "🏔️", es: "La resina para mesa river table (Deep Pour) no puede aplicarse en capas de más de 5 cm a la vez. Más que eso genera calor excesivo y puede agrietarse.", en: "River table (Deep Pour) resin can't be applied in layers over 5 cm at a time. More than that generates too much heat and can crack." },
  { id: "r5", category: "resin", emoji: "🔮", es: "Para efectos de células y lava, mezcla colores diferentes y aplica alcohol isopropílico al 91%+ justo después de verter. El alcohol mueve la resina y crea las células.", en: "For cells and lava effects, mix different colors and apply 91%+ isopropyl alcohol right after pouring. The alcohol moves the resin creating cells." },
  { id: "r6", category: "resin", emoji: "⚖️", es: "Mide siempre por peso (gramos), no por volumen (ml). La diferencia de densidad entre Parte A y B hace que el volumen no sea preciso.", en: "Always measure by weight (grams), not volume (ml). The density difference between Part A and B makes volume measurements inaccurate." },
  { id: "r7", category: "resin", emoji: "🌊", es: "Para una mesa river table: vierte el wood primero, luego rellena con resina. Usa cinta de carrocero en los bordes para contener la resina mientras cura.", en: "For a river table: place the wood first, then fill with resin. Use masking tape on the edges to contain the resin while it cures." },
  { id: "r8", category: "resin", emoji: "🕶️", es: "Protección obligatoria: guantes de nitrilo, gafas de seguridad y ventilación. Los vapores de resina son irritantes y los endurecedores son cáusticos.", en: "Mandatory protection: nitrile gloves, safety goggles, and ventilation. Resin vapors are irritating and hardeners are caustic." },

  // CONCRETE
  { id: "k1", category: "concrete", emoji: "💧", es: "Menos agua = concreto más resistente. Usa la menor cantidad de agua posible mientras la mezcla todavía sea trabajable. Relación agua:cemento ideal: 0.40–0.45.", en: "Less water = stronger concrete. Use as little water as possible while the mix is still workable. Ideal water:cement ratio: 0.40–0.45." },
  { id: "k2", category: "concrete", emoji: "🧤", es: "El cemento es altamente alcalino y puede causar quemaduras en la piel. Usa siempre guantes de goma y evita el contacto prolongado con la piel.", en: "Cement is highly alkaline and can cause skin burns. Always use rubber gloves and avoid prolonged skin contact." },
  { id: "k3", category: "concrete", emoji: "⏱️", es: "El concreto gana el 70% de su resistencia en los primeros 7 días, pero sigue curando 28 días. No cargues una pieza antes de las 72 horas mínimo.", en: "Concrete gains 70% of its strength in the first 7 days, but continues curing for 28 days. Don't load a piece before 72 hours minimum." },
  { id: "k4", category: "concrete", emoji: "🏺", es: "Para piezas decorativas delgadas (macetas, joyería), usa mezcla 1:1 o GFRC con fibra de vidrio. El concreto estándar es demasiado pesado.", en: "For thin decorative pieces (pots, jewelry), use 1:1 mix or GFRC with glass fiber. Standard concrete is too heavy." },
  { id: "k5", category: "concrete", emoji: "💦", es: "Cura el concreto manteniéndolo húmedo los primeros 7 días. Cubrir con plástico evita que el agua se evapore demasiado rápido y la pieza se agriete.", en: "Cure concrete by keeping it moist for the first 7 days. Covering with plastic prevents water from evaporating too fast and the piece cracking." },
  { id: "k6", category: "concrete", emoji: "🎨", es: "Agrega pigmento de óxido de hierro para colorear el concreto en masa. Usa un máximo del 5–10% del peso del cemento para no perder resistencia.", en: "Add iron oxide pigment to color concrete throughout. Use a maximum of 5–10% of cement weight to avoid losing strength." },

  // PLASTER
  { id: "p1", category: "plaster", emoji: "💧", es: "La regla de oro del yeso: SIEMPRE agrega el yeso al agua, nunca al revés. Espolvorea el yeso sobre el agua y espera 1–2 minutos antes de mezclar.", en: "The golden rule of plaster: ALWAYS add plaster TO water, never the other way. Sprinkle plaster on water and wait 1–2 minutes before mixing." },
  { id: "p2", category: "plaster", emoji: "🌀", es: "Mezcla el yeso suavemente con movimientos circulares desde abajo. Nunca batas con fuerza — el aire atrapado crea burbujas que debilitan la pieza.", en: "Mix plaster gently with circular movements from below. Never beat vigorously — trapped air creates bubbles that weaken the piece." },
  { id: "p3", category: "plaster", emoji: "⏱️", es: "El tiempo de trabajo del yeso París es de solo 8–12 minutos. Prepara el molde y todo lo necesario ANTES de mezclar.", en: "Working time for plaster of Paris is only 8–12 minutes. Prepare the mold and everything needed BEFORE mixing." },
  { id: "p4", category: "plaster", emoji: "🌡️", es: "El yeso genera calor al fraguar (reacción exotérmica). Cuando sientas que el molde se calienta, es señal de que está fraguando. Espera que se enfríe antes de desmoldar.", en: "Plaster generates heat as it sets (exothermic reaction). When you feel the mold getting warm, it's setting. Wait for it to cool before demolding." },
  { id: "p5", category: "plaster", emoji: "🏺", es: "Para esculturas detalladas, el Hydrocal/Ultracal (yeso tipo stone) es mejor que el yeso París. Es más resistente y captura mejor los detalles finos.", en: "For detailed sculptures, Hydrocal/Ultracal (stone plaster) is better than Plaster of Paris. It's stronger and captures finer detail." },
  { id: "p6", category: "plaster", emoji: "🔒", es: "Aplica sellador acrílico sobre piezas de yeso terminadas para protegerlas de la humedad. El yeso sin sellar absorbe agua y se puede deteriorar.", en: "Apply acrylic sealer on finished plaster pieces to protect from moisture. Unsealed plaster absorbs water and can deteriorate." },

  // SOAP
  { id: "s1", category: "soap", emoji: "⚗️", es: "La lejía (NaOH) es extremadamente corrosiva. Agrega siempre la lejía AL AGUA, nunca al revés — la reacción es violenta y puede salpicar.", en: "Lye (NaOH) is extremely corrosive. Always add lye TO WATER, never the other way — the reaction is violent and can splatter." },
  { id: "s2", category: "soap", emoji: "🌡️", es: "Para jabón en frío (cold process), mezcla aceites y lejía cuando ambos estén entre 35–45°C. Temperaturas muy diferentes pueden arruinar la saponificación.", en: "For cold process soap, mix oils and lye when both are between 35–45°C. Very different temperatures can ruin saponification." },
  { id: "s3", category: "soap", emoji: "⏱️", es: "El jabón casero necesita curar 4–6 semanas después del desmolde. Durante el curado, el exceso de agua se evapora y el jabón se vuelve más suave para la piel.", en: "Homemade soap needs to cure 4–6 weeks after unmolding. During curing, excess water evaporates and the soap becomes milder on skin." },

  // BUSINESS
  { id: "b1", category: "business", emoji: "💰", es: "El precio de venta mínimo viable es: costos × 3. Esto cubre materiales, tiempo y da un margen decente. Usa el 40% de margen como punto de partida.", en: "The minimum viable selling price is: costs × 3. This covers materials, time, and gives a decent margin. Use 40% margin as a starting point." },
  { id: "b2", category: "business", emoji: "📦", es: "No olvides incluir el empaque en el costo. Una caja bonita puede costar tanto como los materiales del producto — y justifica subir el precio.", en: "Don't forget to include packaging in your cost. A nice box can cost as much as the product materials — and justifies raising the price." },
  { id: "b3", category: "business", emoji: "⏰", es: "Tu tiempo vale dinero. Si tardas 2 horas en hacer 10 velas y no te cobras la hora de trabajo, estás perdiendo dinero aunque 'vendas bien'.", en: "Your time is worth money. If you spend 2 hours making 10 candles and don't charge for your labor, you're losing money even if sales look good." },
  { id: "b4", category: "business", emoji: "📊", es: "Usa el modo 'lote' para calcular el costo de una producción completa. A veces los costos fijos (moldes, energía) solo se amortizan en lotes grandes.", en: "Use the 'batch' mode to calculate the cost of a full production run. Sometimes fixed costs (molds, energy) only amortize in large batches." },
  { id: "b5", category: "business", emoji: "🏷️", es: "El 'precio percibido' importa tanto como el costo real. Una vela artesanal con historia puede venderse 5× más que una industrial del mismo tamaño.", en: "Perceived price matters as much as real cost. An artisan candle with a story can sell 5× more than a same-size industrial one." },
  { id: "b6", category: "business", emoji: "🚚", es: "Si vendes online, incluye el costo de envío en tu cálculo desde el principio. Es el costo más olvidado y puede eliminar todo tu margen.", en: "If you sell online, include shipping cost in your calculation from the start. It's the most forgotten cost and can wipe out your entire margin." },
  { id: "b7", category: "business", emoji: "📱", es: "Guarda cada cálculo con el nombre del producto. Cuando un cliente repita un pedido, tendrás exactamente el costo y precio listos en segundos.", en: "Save each calculation with the product name. When a customer reorders, you'll have the exact cost and price ready in seconds." },

  // GENERAL
  { id: "g1", category: "general", emoji: "📝", es: "Haz siempre una vela / pieza de prueba antes de producir en lote. Los materiales reales varían del teórico — calibra primero, produce después.", en: "Always make a test candle/piece before batch production. Real materials vary from theoretical — calibrate first, produce later." },
  { id: "g2", category: "general", emoji: "🌡️", es: "Un termómetro infrarrojo de cocina es una de las mejores inversiones para este oficio. Control de temperatura = control de calidad.", en: "An infrared kitchen thermometer is one of the best investments for this craft. Temperature control = quality control." },
  { id: "g3", category: "general", emoji: "⚖️", es: "Una balanza de cocina con precisión de 1g es esencial. La mayoría de fórmulas son por peso, no por volumen.", en: "A kitchen scale accurate to 1g is essential. Most formulas are by weight, not volume." },
  { id: "g4", category: "general", emoji: "📸", es: "Fotografía cada pieza antes de venderla. Con el tiempo, tu catálogo visual se convierte en tu mejor herramienta de ventas.", en: "Photograph every piece before selling it. Over time, your visual catalog becomes your best sales tool." },
  { id: "g5", category: "general", emoji: "🧹", es: "Limpia tus herramientas inmediatamente después de usarlas. La cera solidificada, la resina curada o el yeso fraguado son mucho más difíciles de quitar.", en: "Clean your tools immediately after use. Solidified wax, cured resin, or set plaster are much harder to remove later." },
  { id: "g6", category: "general", emoji: "🔄", es: "El 5–15% de desperdicio es normal en producción artesanal. Inclúyelo siempre en el cálculo de materiales — la calculadora lo hace automáticamente.", en: "5–15% waste is normal in handcraft production. Always include it in material calculations — the calculator does this automatically." },
  { id: "g7", category: "general", emoji: "📦", es: "Compra materiales en cantidades más grandes para reducir el costo por gramo. Pero calcula si el ahorro justifica la inversión inicial.", en: "Buy materials in larger quantities to reduce cost per gram. But calculate whether the savings justify the upfront investment." },
  { id: "g8", category: "general", emoji: "💾", es: "¿Encontraste la fórmula perfecta? Guárdala ahora. En la biblioteca puedes almacenar tus recetas favoritas y reutilizarlas en cualquier momento.", en: "Found the perfect formula? Save it now. In the library you can store your favorite recipes and reuse them anytime." },
  { id: "g9", category: "general", emoji: "🎯", es: "Para empezar, elige UN producto y perfecciónalo completamente antes de diversificar. La especialización construye reputación más rápido.", en: "To start, choose ONE product and perfect it completely before diversifying. Specialization builds reputation faster." },
  { id: "g10", category: "general", emoji: "🌍", es: "Los precios varían mucho por región. Usa el campo de moneda para ajustar tu mercado local y la calculadora adaptará los resultados.", en: "Prices vary a lot by region. Use the currency field to adjust for your local market and the calculator will adapt the results." },
  { id: "g11", category: "general", emoji: "🔬", es: "El porcentaje de desperdicio real solo lo conoces produciendo. Después de 10 lotes, tendrás un número preciso para tu proceso específico.", en: "Your real waste percentage is only known through production. After 10 batches, you'll have a precise number for your specific process." },
  { id: "g12", category: "general", emoji: "🤝", es: "Exporta el PDF de cada presupuesto para compartir con proveedores o clientes. Un presupuesto profesional transmite confianza.", en: "Export the PDF of each quote to share with suppliers or clients. A professional quote transmits confidence." },
];

export function getRandomTip(locale: string, category?: string): Tip {
  const filtered = category ? TIPS.filter(t => t.category === category || t.category === "general" || t.category === "business") : TIPS;
  return filtered[Math.floor(Math.random() * filtered.length)];
}

export function getTipText(tip: Tip, locale: string): string {
  return locale === "es" ? tip.es : tip.en;
}
